<?php

namespace Solvre\Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * DiagramRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DiagramRepository extends EntityRepository
{
}
