<?php

namespace Solvre\Model\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * PlanTaskRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PlanTaskRepository extends EntityRepository
{
}
