<?php

namespace Solvre\Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
}
