<?php

namespace Solvre\Model\Doctrine\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserInProjectRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserInProjectRepository extends EntityRepository
{
}
